name: Build JavaScript assets

on:
  push:
    branches:
      - acpl-fork

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: flarum/action-build@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

